export enum ACTION {
  CREATE_USER = 'CREATE_USER',
  LOGIN = 'LOGIN',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
  ATTACH_ROLE_TO_USER = 'ATTACH_ROLE_TO_USER',
  CREATE_ROLE = 'CREATE_ROLE',
  CREATE_PERMISSION = 'CREATE_PERMISSION',
  UPDATE_PERMISSION = 'UPDATE_PERMISSION',
  DELETE_PERMISSION = 'DELETE_PERMISSION',
  DETACH_PERMISSION_FROM_ROLE = 'DETACH_PERMISSION_FROM_ROLE',
  ATTACH_PERMISSION_TO_ROLE = 'ATTACH_PERMISSION_TO_ROLE',
}
