services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    env_file:
      - .env
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --event_scheduler=ON
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    logging:
      driver: 'none'

volumes:
  mysql-data:
