/* DO NOT EDIT, file generated by nestjs-i18n */

/* prettier-ignore */
import { Path } from "nestjs-i18n";

/* prettier-ignore */
export type I18nTranslations = {
    "error": {
        "USER_ALREADY_EXISTS": string;
    };
    "message": {
        "USER_REGISTRATION_SUCCESS": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
